### PR TITLE
Native Posix support (arch/posix_x86) + multiarch builds

### PR DESCRIPTION
**Pull request by proger**
This is based on `arm` port which has less xen hooks throughout generic code and introduces a new architecture, `posix` which is supposed to use the syscall API for core functionality, the only drivers currently implemented are `mm` (using `mmap(2)`) and `console` (using stdin/stdout).

Build system: removes the need for GNU `objcopy(1)` during build steps in favour of `bfd_objcopy` module that only uses the C compiler (generates a C file) to achieve embedding files into binaries.
Linking steps ignore linker scripts (because Darwin linker doesn't support them) but so far the default `compiler_rt` layout + `image_base` work out well.

The current state of the assumes does not use the embedded libc (aka `lib/misc`) in favour of `libSystem` and embedded nettle (I'm not going to keep it that way).

Can be tested by running `railing -a image` (`-a` is short for `apple`)

Submitting the PR now for early feedback. Haven't got to running the test suite yet.

### CODE REVIEW

**Comment by proger** [comment]
I've brought xen code back into the tree (with most files being placed at `arch/x86`), making the merge sequence of `osx-again -> raspberry-pi -> master` simple. I'm going to add build tests for all platforms at once.

**Comment by proger** [comment]
At this point I'm able to build posix and xen flavours of ling from a single (clean) source tree using  `make ARCH=posix` and `make ARCH=x86` (one a mac using a cross-toolchain for ling). Going to test arm builds next.

**Comment by maximk** [comment]
@proger we may need x86-posix and x86-xen for architectures instead (and
arm-baremetal).

**Comment by proger** [comment]
Agreed, I'm putting the rename part off to simplify running `diff`. :)

**Comment by proger** [comment]
At this point I'm ready for merging. The architectures have been renamed, the only necessary build steps now are `make ARCH=arch_name` in the root of the project with a clean working copy. `vagrant up` should produce a working build for `arm`.

To move forward, I suggest merging this into `raspberry_pi` and immediately into `master` to continue making the port useful.

Let me know if you want to squash my commits.

**Comment by krant** [comment]
xen_x86 is broken, 'railing image' produsing this:
```
railing build arch: xen_x86
Generate: railing.img
Run: /usr/bin/cc -o /home/krant/ling_proger/railing/.railing/embedfs.o -c /home/krant/ling_proger/railing/.railing/embedfs.c
Run: /usr/bin/ld -T ling.lds -nostdlib vmling.o /home/krant/ling_proger/railing/.railing/embedfs.o -o ../railing.img
vmling.o: In function `ets_table_make':
/home/krant/ling_proger/core/ets.c:193: undefined reference to `longjmp'
vmling.o: In function `ets_table_rename':
/home/krant/ling_proger/core/ets.c:272: undefined reference to `longjmp'
vmling.o: In function `ets_set_opt':
/home/krant/ling_proger/core/ets.c:327: undefined reference to `longjmp'
vmling.o: In function `ets_marshal_object':
/home/krant/ling_proger/core/ets.c:578: undefined reference to `longjmp'
vmling.o: In function `ets_demarshal_object':
/home/krant/ling_proger/core/ets.c:624: undefined reference to `longjmp'
vmling.o:/home/krant/ling_proger/core/ext_term.c:972: more undefined references to `longjmp' follow
vmling.o: In function `start_ling':
/home/krant/ling_proger/core/ling.c:165: undefined reference to `setjmp'
vmling.o: In function `nalloc':
/home/krant/ling_proger/core/nalloc.c:74: undefined reference to `longjmp'
vmling.o: In function `ets_hash_insert_many':
/home/krant/ling_proger/core/ets_hash.c:438: undefined reference to `longjmp'
vmling.o: In function `ets_hash_first':
/home/krant/ling_proger/core/ets_hash.c:598: undefined reference to `longjmp'
vmling.o: In function `ets_hash_next':
/home/krant/ling_proger/core/ets_hash.c:646: undefined reference to `longjmp'
vmling.o: In function `start_timer':
/home/krant/ling_proger/core/bif_sys.c:839: undefined reference to `longjmp'
vmling.o:/home/krant/ling_proger/core/bif_generic.c:888: more undefined references to `longjmp' follow
vmling.o: In function `proc_main':
/home/krant/ling_proger/core/ling_main.c:237: undefined reference to `setjmp'
/home/krant/ling_proger/core/ling_main.c:11434: undefined reference to `longjmp'
/home/krant/ling_proger/core/ling_main.c:27579: undefined reference to `longjmp'
/home/krant/ling_proger/core/ling_main.c:27748: undefined reference to `longjmp'
Generate: domain_config
```

**Comment by krant** [comment]
Also '-flto' option is crucial for lib/misc performance, do not kill it.
'-fexcess-precision=standard -frounding-math' is also recommended settings, e.g. musl was built with them.

**Comment by proger** [comment]
@krant 

> Also '-flto' option is crucial for lib/misc performance, do not kill it.
> '-fexcess-precision=standard -frounding-math' is also recommended settings, e.g. musl was built with them

Thanks, I forgot to bring those options in.

> vmling.o: In function `ets_table_make':
> /home/krant/ling_proger/core/ets.c:193: undefined reference to `longjmp'

What compiler / OS are you testing with? I was using [cross-gcc 4.8.1 on a mac](http://crossgcc.rts-software.org/doku.php?id=compiling_for_linux).

**Comment by krant** [comment]
gcc 4.9.2 on Arch Linux. I just noticed that Travis is also failing - https://travis-ci.org/cloudozer/ling/builds/57831248#L3371, in spite of railing reporting success.

**Comment by proger** [comment]
Regression introduced in https://github.com/proger/ling/commit/4a1ee937c48dabd3305bb8bfa0f28ea62cccfd3e fixed in https://github.com/proger/ling/commit/d9161292b4f715a08cf031bda99b470bc4fc92c4.

**Comment by krant** [comment]
Everything built! Now test.img silently crashing on 'xl create', 'xl dmesg' shows:

```
(XEN) grant_table.c:1305:d15v0 Expanding dom (15) grant table from (4) to (32) frames.
(XEN) traps.c:524:d15v0 Unhandled general protection fault fault/trap [#13] on VCPU 0 [ec=0000]
(XEN) domain_crash_sync called from entry.S: fault at ffff82d080231169 create_bounce_frame+0x139/0x148
(XEN) Domain 15 (vcpu#0) crashed on cpu#3:
(XEN) ----[ Xen-4.6-unstable  x86_64  debug=y  Not tainted ]----
(XEN) CPU:    3
(XEN) RIP:    e033:[<00000000000ea6bc>]
(XEN) RFLAGS: 0000000000000202   EM: 1   CONTEXT: pv guest
(XEN) rax: 0064036862010064   rbx: 000000000000004b   rcx: 000000000000000b
(XEN) rdx: 000000000029206b   rsi: 0000000000a5705c   rdi: 0000000000f46810
(XEN) rbp: 0000000000a6ff70   rsp: 0000000000a57000   r8:  000000000000004b
(XEN) r9:  0000000000a31ac4   r10: 0000000000f167d0   r11: 0000000000000003
(XEN) r12: 0000000000a31ae0   r13: 0000000000041039   r14: 00000000000472e9
(XEN) r15: 0000000000eda048   cr0: 0000000080050033   cr4: 00000000001526f0
(XEN) cr3: 000000014212c000   cr2: 0000000000000000
(XEN) ds: 0000   es: 0000   fs: 0000   gs: 0000   ss: e02b   cs: e033
(XEN) Guest stack trace from rsp=0000000000a57000:
(XEN)    000000000000000b 0000000000000003 0000000000000000 00000000000ea6bc
(XEN)    000000010000e030 0000000000010002 0000000000a57040 000000000000e02b
(XEN)    0000000000a6ff70 00000000000ce543 0000000000041039 0000004b000472e9
(XEN)    0000000000eda048 0000000000050ebf 0000000000a306f4 0000000000a2f828
(XEN)    0000000000a2f6f0 000000000004b7ec 000000000004ac25 000000000004c17c
(XEN)    000000000004ed2a 0000000000043321 0000000000a2fe78 0000000000a2fdd4
(XEN)    000000000005085b 0000000000059b26 0000000000a2f628 0000000000040890
(XEN)    0000000000040ba2 0000000000046bde 000000000005190c 0000000000a2f2f4
(XEN)    0000000000a2df44 0000000000a2e05c 0000000000a2f09c 0000000000a2fb3c
(XEN)    0000000000a2f028 0000000000a2e234 0000000000a2e1ac 0000000000a2e0e0
(XEN)    0000000000041f84 0000000000041f44 0000000000a2d80c 0000000000047a5d
(XEN)    0000000000a2d088 0000000000a2ce90 0000000000a2f438 000000000004f5b1
(XEN)    0000000000a2c360 0000000000047b29 0000000000042937 0000000000a2ccac
(XEN)    0000000000a2cf74 0000000000a2cd0c 00000000000546d2 000000000005bb1e
(XEN)    0000000000a2bdc0 0000000000056b78 0000000000046690 0000000000054f93
(XEN)    0000000000a2b1e0 000000000005829a 0000000000a2a9e8 0000000000059ebd
(XEN)    0000000000a2b09c 0000000000052efb 0000000000040d52 00000000000c7900
(XEN)    0000000000a2b240 0000000000a2d014 0000000000a2ced8 0000000000a2b244
(XEN)    0000000000050a53 00000000000464ac 00000000000c8560 00000000000438fb
(XEN)    0000000000a2a2d4 0000000000a2a4fc 0000000000a2a514 0000000000a2a51c
```

Also memory reqs for image generation stage became enormous, i had to kill chromium on my 4GB laptop to build test.img:
```
Generate: test.img

Crash dump was written to: erl_crash.dump
eheap_alloc: Cannot allocate 762886488 bytes of memory (of type "heap", thread 1).
```

**Comment by proger** [comment]
Thanks for the tests, comments below:

> Everything built! Now test.img silently crashing on 'xl create', 'xl dmesg' shows

There must have been a copy-paste issue when I was merging code `raspberry_pi` with `master` — I haven't tested any of the Xen stuff assuming it works if it builds. I'm going to address this by adding a runtime test to a `Vagrantfile` along with arm.

> Also memory reqs for image generation stage became enormous, i had to kill chromium on my 4GB laptop to build test.img

This must be a performance issue in [bfd_obcopy](https://github.com/proger/ling/blob/osx-again/bc/bfd_objcopy.erl), I'll look into it.

**Comment by proger** [comment]
Closing as this is obviously outdated.
